[package]
name = "re0box"
version = "0.1.0"
authors = ["descawed <re0box@descawed.com>"]
edition = "2021"
description = "An item box mod for Resident Evil 0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.*"
binrw = "0.11.*"
configparser = "3.0.*"
windows = { version = "0.48.*", features = [ "Win32_Foundation", "Win32_System_Memory", "Win32_System_SystemServices" ] }